#pragma config(Motor,  port2,           right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           toplift,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           bottotmlift,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mogoR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mogoL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           top4bar,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void moveLift(int power) {
	motor[topLift] = power;
	motor[bottomLift] = power;
}

void moveMogo(int power) {
	motor[mogoR] = power;
	motor[mogoL] = power;
}

void moveTop4bar(int power) {
	motor[top4bar] = power;
}

void claw(int power) {
	motor[claw] = power;
}
task main()
{
	while(true)
		{
			motor[right] = vexRT[Ch2];
			motor[left] = vexRT[Ch3];


			if(vexRT[Btn6U] == 1) {
				moveLift(127);
			} else if (vexRt[Btn6D]) {
				moveLift(-127);
			}


			if(vexRT[Btn5U] == 1) {
			  moveMogo(127);
			} else if (vexRt[Btn5D]) {
				moveMogo(-127);
			}

			if(vexRT[Btn8U] == 1) {
			  moveTop4bar(127);
			} else if (vexRt[Btn8D]) {
				moveTop4bar(-127);
			}

			if(vexRT[Btn8L] == 1) {
			  claw(127);
			} else if (vexRt[Btn8R]) {
				claw(-127);
			}











}
