#pragma config(Motor,  port2,           right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           toplift,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           bottomlift,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mogoR,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mogoL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           top4bar,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void moveLift(int power) {
	motor[toplift] = power;
	motor[bottomlift] = power;
}

void moveMogo(int power) {
	motor[mogoR] = power;
	motor[mogoL] = power;
}

void moveTop4bar(int power) {
	motor[top4bar] = power;
}

void drive
(int power) {
	motor[right] = power;
	motor[left] = power;
}

void coneclaw(int power) {
	motor[claw] = power;

}


task main()
{
	while(true)
	{
		motor[right] = vexRT[Ch2];
		motor[left] = vexRT[Ch3];


		if(vexRT[Btn6U] == 1) {
			moveLift(127);
			} else if (vexRT[Btn6D]) {
			moveLift(-127);
			} else {
			moveLift(0);
		}


		if(vexRT[Btn5U] == 1) {
			moveMogo(127);
			} else if (vexRT[Btn5D]) {
			moveMogo(-127);
			} else {
			moveMogo(0);
		}

		if(vexRT[Btn8U] == 1) {
			moveTop4bar(127);
			} else if (vexRT[Btn8D]) {
			moveTop4bar(-127);
			} else {
			moveTop4bar(0);
		}

		if(vexRT[Btn8L] == 1) {
			coneclaw(127);
			} else if (vexRT[Btn8R]) {
			coneclaw(-127);
			} else {
			coneclaw(0);
		}











	}
}
