#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in3,    RightLiftPot,   sensorPotentiometer)
#pragma config(Sensor, in4,    LeftLiftPot,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           LeftDrive,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           RightDrive,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           RightLift,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LeftLift,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           LeftMobileGoal, tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           RightMobileGoal, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           SwitchLift,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           Claw,          tmotorVex393HighSpeed_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

#include "motor.h"
#include "pid.c"
#include "autonomous.c"
#include "Vex_Competition_Includes.c"

void pre_auton() {
	bStopTasksBetweenModes = true;

	SensorType[in1] = sensorNone;
	delay(1500);

	SensorType[in1] = sensorGyro;
	delay(1500);
}

task autonomous() {
	auto();
}

task usercontrol() {
	datalogClear();
	pid config;
	pid rconfig;
	config.kp = 0.3;
	config.ki = 0;
	config.kd = 0;
	config.dt = 20;

	while (true) {
		// drive code
		moveDrive(vexRT[Ch3], vexRT[Ch2]);

		// lift code
		if (vexRT[Btn5U]) {
			moveLift(127);
			stopPid();
			} else if (vexRT[Btn5D]) {
			moveLift(-127);
			stopPid();
			} else {
			if (!isRunning()) {
				moveLift(0);
			}
		}

		if (vexRT[Btn6U]) {
			openClaw(127);
			} else if (vexRT[Btn6D]) {
			closeClaw(127);
			} else {
			stopClaw();
		}

		if (vexRT[Btn8L]) {
			moveGoal(127);
			} else if (vexRT[Btn8R]) {
			moveGoal(-127);
			} else {
			moveGoal(0);
		}

		if (vexRT[Btn7U]) {
			moveSwitchLift(127);
			} else if (vexRT[Btn7D]) {
			moveSwitchLift(-127);
			} else {
			moveSwitchLift(0);
		}
		if (vexRT[Btn7L]) {
			startPid(SensorValue[LeftLiftPot], config, rconfig);
			} else if (vexRT[Btn7R]) {
			stopPid();
		}
	}
}
