#pragma config(Sensor, dgtl10,          encLeft,       sensorQuadEncoder)
#pragma config(Sensor, dgtl12,          encRight,      sensorQuadEncoder)
#pragma config(Motor,  port2,           right,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           toplift,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           bottomlift,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           mongo_right,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mongo_left,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           top_fourbar,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// while vexRT[Btn6U] is being run: dont run pid
// encoders: sensorValue[encLeft/encRight]
// 3600 ticks per revolution
// 10 ticks per degree
void moveLift(int speed) {
		motor[toplift] = speed;
		motor[bottomlift] = speed;
}

void drive(int distance) {
	while (sensorValue[encLeft] < ) {

	}
}
task holdLift() {
	writeDebugStreamLine("PID loop is running");
	int SCALE_PROPORTIONAL = 0.05;
  int SCALE_INTEGRAL = 0.005;
  int INT_MAX = SCALE_PROPORTIONAL * 30;
  int INT_MIN = SCALE_PROPORTIONAL * 20;
	int integral = 0;
	int proportional = 0;
	int total = 0;
	while (!vexRT[Btn6U]) {
		writeDebugStreamLine("PID loop is in progress");
		int error;
		proportional = SCALE_PROPORTIONAL * error;
		integral += SCALE_INTEGRAL * error;
		if (integral > INT_MAX) {
			integral = INT_MAX;
		}
		else if (integral < INT_MIN) {
			integral = INT_MIN;
		}
		total = proportional + integral;
		moveLift(total);
		wait1Msec(20);
	}
	writeDebugStreamLine("PID Loop is stopping");
}

task main() {
	startTask(holdLift);
	writeDebugStreamLine("main is running");
	while (true) {
		// stalls the program infinitely without using the CPU too much
		wait(1000);
	}
}
