#pragma config(Sensor, in2,    gyro,           sensorGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	SensorType[gyro] = sensorNone;
	delay(1500);

	SensorType[gyro] = sensorGyro;
	delay(1500);
	while (true) {
	}
}
