#pragma config(Sensor, in2,    gyro,           sensorGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "build_stack.c"

task main()
{
	while (true) {
		if (vexRT[Btn5D]) {
			buildStack(5);
		}
	}
}
