#pragma config(Sensor, in2,    gyro,           sensorGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "pragma.h"
#include "build_stack.c"
#include "stall.c"
#include "motor.h"

task main()
{
	while (true) {
		if (vexRT[Btn5D]) {
			buildStack(5);
		}

		if (vexRT[Btn7U]) {
			moveLift(100);
		}
		else if (vexRT[Btn7D]) {
			moveLift(-100);
		}
		else {
			applyStall();
		}
		delay(20);s
	}
}
